name: Deploy client to GitHub Pages
env:
  VITE_ATOM_SOCKET_API: ${{ secrets.VITE_ATOM_SOCKET_API }}

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack and activate Yarn 4.1.0
        run: |
          corepack enable
          corepack prepare yarn@4.1.0 --activate

      - name: Set up Node and enable Corepack
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Install dependencies (Yarn workspace)
        run: yarn install --frozen-lockfile

      - name: Build client package
        run: yarn workspace client build

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact from client
        uses: actions/upload-pages-artifact@v3
        with:
          path: client/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
