name: Deploy server to Fly.io

on:
  push:
    paths:
      - "server/**"
      - "games/**"
      - "yarn.lock"
      - ".yarnrc.yml"
      - ".github/workflows/deploy-server.yml"
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    environment: github-pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "${HOME}/.fly/bin" >> $GITHUB_PATH

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
